### ISSUE TITLE
Year of TED tenders

### ISSUE THREAD

**Issue by georgiana-b** [georgiana-b/defense-elvis-backend#16]
For manual data, the year that we display represents the award year. 
For TED data, we generally display the Contract Notice dispatch date and fall back to  the Contract Award Notice dispatch date otherwise. 

So essentially, for TED data we choose the year of the most recent mention of the tender whereas for manual data the year is always the last mention of the tender (after it was already awarded and finalised).
This is a bit of a problem for TED data because sometimes tenders that are started in one year end up finalised (awarded) the following year. 
Shall we start using the year of the last award as the date of the tender for TED data as well?

**Comment by zufanka** [comment]
Yes, that sounds good!
