### ISSUE TITLE
Import defense data from Opentender 

### ISSUE THREAD

**Issue by georgiana-b** [georgiana-b/defense-elvis-backend#3]
As discussed with our partners, most of the defense Elvis data will come from Opentender. We already have the infra for these, we just need to filter only the contracts that are relevant in the context of defense.

**Comment by georgiana-b** [comment]
@zufanka Could you please share the exact criteria tenders need to meet in order to qualify as defense tenders?

**Comment by zufanka** [comment]
[military_cpv.xlsx](https://github.com/georgiana-b/defense-elvis-backend/files/2942586/military_cpv.xlsx)

military CPVs are in the "military" sheet. The codes have a weird form, like 35321000-0 or 35340000-9. from my experience of filtering the data I believe that the number after the dash '-' is not necessary, so I think you can safely filter on 35321000 or 35340000 instead. please double-check though.

Another tenders were filtered according to having to make with a certain directive. This piece of info is afaik not present in the opentender data, only in the TED xmls.

**Comment by georgiana-b** [comment]
This was partially solved in #6. I still have to handle the tenders from opentender that don't have military CPVs but are fall under the Directive 2009/81/EC.
